In [14]:
import pandas

import warnings
def ignore_warn(*args, **kwargs):
    pass
warnings.warn = ignore_warn

# imported the CSV data
dataframe = pandas.read_csv("Filtered_Data.csv", sep = ",")

# Remove the same prefix from all columns names
dataframe.columns  = [ column_name.split('.')[1] for column_name in dataframe.columns ]

dataframe.head()

,ts,impression_system_date,hour,conversion_status,cc_id_null_ind,ad_id,click_id,cc_id,hour_of_day,raw_publisher_id,...,click_conf_gmt_offset,click_state,click_city,ad_bid,ad_cpa_goal,ad_market_place_id,click_click_status,kmean_category_name,partner_id,version
0,20190106,2019-01-06,1,1,0,138154,646739319951006038,546739320882001606,20,8CUDMGV55,...,-500,ga,atlanta,0.150000,NaN,1027,1,missing,8PRHGG6T9,1
1,20190106,2019-01-06,1,1,0,138154,646739319951006038,546739320882001606,20,8CUDMGV55,...,-500,ga,atlanta,0.150000,NaN,1027,1,missing,8PRHGG6T9,1
2,20190106,2019-01-06,2,0,0,138154,646740715393002311,346740715723006848,20,8CUDMGV55,...,-600,al,birmingham,0.150000,NaN,1027,1,missing,8PRHGG6T9,1
3,20190106,2019-01-06,4,0,0,138154,246748175931002645,446748176329007771,23,8CUDMGV55,...,-500,in,ft wayne,0.150000,NaN,1027,1,missing,8PRHGG6T9,1
4,20190106,2019-01-06,6,0,0,128699,246754980029002839,646754981260002933,22,8CUX8874N,...,-800,ca,mountain view,3.394224,NaN,1027,1,missing,8PRHGG6T9,1

In [15]:
# removing all data having single values in entire columns
for col in dataframe.columns:
    if(dataframe[col].nunique() == 1):
        dataframe = dataframe.drop(col, axis = 1)

In [16]:
# Remove the timestamp data and impression system date data - results not dependent on the time frame
dataframe = dataframe.drop('ts', axis = 1)
dataframe = dataframe.drop('impression_system_date', axis = 1)

# Server hour do not matters
dataframe = dataframe.drop('hour', axis = 1)

# Data have only 3 values of *au* region, and conversion status 0 for all of them
dataframe = dataframe.drop('enriched_country', axis = 1)

# Data is similar to cvr_base_data_table.click_city
dataframe = dataframe.drop('impression_city', axis = 1)

# Ad-Bid is the cost which is irrespecti   ve of conversion from user side
dataframe = dataframe.drop('ad_bid', axis = 1)

# Ad CPA goal do not affects the conversion status
dataframe = dataframe.drop('ad_cpa_goal', axis = 1)

# Click Conf GMT Offset do not affects the conversion status
dataframe = dataframe.drop('click_conf_gmt_offset', axis = 1)

# Date Time do not affects and is too granuler to looku[, thus do not affects the conversion status
dataframe = dataframe.drop('click_user_datetime', axis = 1)

# Publisher Domain do not affects the conversion status
dataframe = dataframe.drop('enriched_publisher_domain', axis = 1)

# Impression ISP Name do not affects the conversion status
dataframe = dataframe.drop('impression_isp_name', axis = 1)

In [17]:
dataframe.head()

,conversion_status,ad_id,click_id,cc_id,hour_of_day,raw_publisher_id,raw_sub_publisher_id,raw_sub_sub_publisher_id,enriched_derived_device,enriched_derived_os,...,impression_state,impression_asn_code,impression_connection_type,analyzer_name,category_name,click_browser,raw_sync_partner_id,click_state,click_city,partner_id
0,1,138154,646739319951006038,546739320882001606,20,8CUDMGV55,8PO1W66UO,429821366,mobile,android,...,ga,22394,mobile,keywordanalyserv2,"shopping,consumer,resources,coupons,,,discount...","google,chrome",1,ga,atlanta,8PRHGG6T9
1,1,138154,646739319951006038,546739320882001606,20,8CUDMGV55,8PO1W66UO,429821366,mobile,android,...,ga,22394,mobile,keywordanalyserv2,"shopping,consumer,resources,coupons,,,discount...","google,chrome",1,ga,atlanta,8PRHGG6T9
2,0,138154,646740715393002311,346740715723006848,20,8CUDMGV55,8PO1W66UO,110622874,mobile,android,...,al,21928,mobile,keywordanalyserv2,"shopping,consumer,resources,coupons,,,discount...","google,chrome",1,al,birmingham,8PRHGG6T9
3,0,138154,246748175931002645,446748176329007771,23,8CUDMGV55,8PO1W66UO,110622874,mobile,android,...,in,7922,cable,keywordanalyserv2,"shopping,consumer,resources,coupons,,,discount...","google,chrome",1,in,ft wayne,8PRHGG6T9
4,0,128699,246754980029002839,646754981260002933,22,8CUX8874N,8PO4X3YG2,670653476,mobile,android,...,ca,15169,broadband,keywordanalyserv2,"finance,grants,,scholarships,,,financial,aid","google,chrome",1,ca,mountain view,8PRHGG6T9